// action Shop
export const LOAD_SHOP_REQUEST = 'LOAD_SHOP_REQUEST'
export const LOAD_SHOP_SUCCESS = 'LOAD_SHOP_SUCCESS'
export const LOAD_SHOP_FAILURE = 'LOAD_SHOP_FAILURE'

export const LOAD_SHOP_BY_BRAND_REQUEST = 'LOAD_SHOP_BY_BRAND_REQUEST'
export const LOAD_SHOP_BY_BRAND_SUCCESS = 'LOAD_SHOP_BY_BRAND_SUCCESS'
export const LOAD_SHOP_BY_BRAND_FAILURE = 'LOAD_SHOP_BY_BRAND_FAILURE'

export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'

// action Product
export const LOAD_PRODUCT_REQUEST = 'LOAD_PRODUCT_REQUEST'
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS'
export const LOAD_PRODUCT_FAILURE = 'LOAD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT_VIEWS_REQUEST = 'UPDATE_VIEWS_REQUEST'
export const UPDATE_PRODUCT_VIEWS_SUCCESS = 'UPDATE_VIEWS_SUCCESS'
export const UPDATE_PRODUCT_VIEWS_FAILURE = 'UPDATE_VIEWS_FAILURE'

export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'

// action Search
export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAILURE = 'SEARCH_PRODUCT_FAILURE'

export const CLEAR_SEARCH = 'CLEAR_SEARCH'

// action User
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const GET_USERNAME_REQUEST = 'GET_USERNAME_REQUEST'
export const GET_USERNAME_SUCCESS = 'GET_USERNAME_SUCCESS'
export const GET_USERNAME_FAILURE = 'GET_USERNAME_FAILURE'

export const GET_EMPLOYEE_DETAIL_REQUEST = 'GET_EMPLOYEE_DETAIL_REQUEST'
export const GET_EMPLOYEE_DETAIL_SUCCESS = 'GET_EMPLOYEE_DETAIL_SUCCESS'
export const GET_EMPLOYEE_DETAIL_FAILURE = 'GET_EMPLOYEE_DETAIL_FAILURE'

export const GET_CUSTOMER_DETAIL_REQUEST = 'GET_CUSTOMER_DETAIL_REQUEST'
export const GET_CUSTOMER_DETAIL_SUCCESS = 'GET_CUSTOMER_DETAIL_SUCCESS'
export const GET_CUSTOMER_DETAIL_FAILURE = 'GET_CUSTOMER_DETAIL_FAILURE'

export const REGISTER_CUSTOMER_REQUEST = 'REGISTER_CUSTOMER_REQUEST'
export const REGISTER_CUSTOMER_SUCCESS = 'REGISTER_CUSTOMER_SUCCESS'
export const REGISTER_CUSTOMER_FAILURE = 'REGISTER_CUSTOMER_FAILURE'

// action Cart
export const ADD_TO_CART = 'ADD_TO_CART'

export const LOAD_CART_ITEM_SUCCESS = 'LOAD_CART_ITEM_SUCCESS'
export const LOAD_CART_ITEM_FAILURE = 'LOAD_CART_ITEM_FAILURE'
export const LOAD_CART_ITEM_REQUEST = 'LOAD_CART_ITEM_REQUEST'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

// action Order
export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST'
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS'
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE'

export const LOAD_ORDER_REQUEST = 'LOAD_ORDER_REQUEST'
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS'
export const LOAD_ORDER_FAILURE = 'LOAD_ORDER_FAILURE'

// action ManageProduct
export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PROUDCT_FAILURE = 'CREATE_PRODUCT_FAILURE'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PROUDCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

//action ManageCustomer
export const LOAD_CUSTOMERS_REQUEST = 'LOAD_CUSTOMERS_REQUEST'
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS'
export const LOAD_CUSTOMERS_FAILURE = 'LOAD_CUSTOMERS_FAILURE'

export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE'

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE'

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE'

//action ManageSupplier
export const LOAD_SUPPLIERS_REQUEST = 'LOAD_SUPPLIERS_REQUEST'
export const LOAD_SUPPLIERS_SUCCESS = 'LOAD_SUPPLIERS_SUCCESS'
export const LOAD_SUPPLIERS_FAILURE = 'LOAD_SUPPLIERS_FAILURE'

export const CREATE_SUPPLIER_REQUEST = 'CREATE_SUPPLIER_REQUEST'
export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS'
export const CREATE_SUPPLIER_FAILURE = 'CREATE_SUPPLIER_FAILURE'

export const UPDATE_SUPPLIER_REQUEST = 'UPDATE_SUPPLIER_REQUEST'
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS'
export const UPDATE_SUPPLIER_FAILURE = 'UPDATE_SUPPLIER_FAILURE'

export const DELETE_SUPPLIER_REQUEST = 'DELETE_SUPPLIER_REQUEST'
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS'
export const DELETE_SUPPLIER_FAILURE = 'DELETE_SUPPLIER_FAILURE'
